# Generated by Django 4.1.2 on 2022-11-20 22:59

from django.db import migrations, models
import django.db.models.deletion
import users.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            bases=(models.Model, users.models.TimeStamps),
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            bases=(models.Model, users.models.TimeStamps),
        ),
        migrations.CreateModel(
            name='Sub_Domain',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('domain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.domain')),
            ],
            bases=(models.Model, users.models.TimeStamps),
        ),
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(default=1, max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('dataset_file_name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('host_link', models.FilePathField(blank=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=8)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('pub_by', models.CharField(default='Owner', max_length=200)),
                ('License', models.CharField(default='Open source', max_length=200)),
                ('total_records', models.IntegerField(blank=True, default=0)),
                ('file_size', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=8)),
                ('total_columns', models.IntegerField(blank=True, default=0)),
                ('completeness', models.DecimalField(blank=True, decimal_places=3, default=0.0, max_digits=3)),
                ('timeliness', models.CharField(max_length=200)),
                ('sample', models.JSONField(blank=True)),
                ('column_summary', models.JSONField(blank=True)),
                ('domain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.domain')),
            ],
            bases=(models.Model, users.models.TimeStamps),
        ),
    ]
