# Generated by Django 4.1.7 on 2023-02-18 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sub_domain',
            name='domain',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
        migrations.DeleteModel(
            name='Sub_Domain',
        ),
    ]
